### ISSUE TITLE
purpose of ActionContextAccessor DI setup

### ISSUE THREAD

**Issue by drdamour** [EtiennePeeters/AzureFunctionsRazorEmailTemplateSample#1]
what's the purpose of .AddSingleton<IActionContextAccessor, ActionContextAccessor>() in your startup?  I wasn't seeing you use it anywhere and when i get a handle to it the actioncontext for it is always null

**Comment by EtiennePeeters** [comment]
Good catch! It is indeed not used. I forgot to remove that line after trying to get the ActionContext that way. 3ece949f3832e93ffd6882a114911a1e66c992af
