### ISSUE TITLE
purpose of PostBuild Target

### ISSUE THREAD

**Issue by drdamour** [EtiennePeeters/AzureFunctionsRazorEmailTemplateSample#2]
trying to grok this...it's not clear to me what the postbuild target you have is doing/why t's needed

```
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <OutputFiles Include="$(OutDir)Views\*"></OutputFiles>
    </ItemGroup>
    <Move SourceFiles="@(OutputFiles)" DestinationFolder="$(OutDir)bin" OverwriteReadOnlyFiles="true"></Move>
  </Target>
```

i don't see any differences in output with this enabled or commented out...is this an attempt to make live editing function?

**Comment by EtiennePeeters** [comment]
This is a leftover of me trying to get this to work, before I learned to access the views with `Assembly.LoadFile()` on the views assembly.
I thought it would be nice to be able to edit the views without rebuilding the application, but I couldn't get that to work.

Removed it, thanks. 71b7224f92e9ddabb32c1efb235a556d14763a65

**Comment by drdamour** [comment]
Yeah i tried like hell to get runtime compilation working...
first just bringing in the assembly makes the sdk not publish the startup extension for whatever reason..i dont understand functions enough to know why this happened. Easy enough to hack around to attempt

Then the dependencies of the runtime compilation assembly are not moved to the netcoreapp/bin directory so they cant be loaded... again im at a loss but easy enough to copy paste some stuff to get past for a bit

Then runtime compilation was looking in /netcoreapp/bin for the views.  Again easy enough to add a file provider to the project root

Then and only then did i give up the runtime compilation said it couldnt load Microsoft namespace or System.Type on and on. Im guessing it uses its own app domain, but how can it not find the most basic types? Really confusing
